### ISSUE TITLE
Undefined array key "X-Rate-Limit-Limit"

### ISSUE THREAD

**Issue by azamar-onnit** [pixelpeter/laravel-genderize-api-client#1]
Since the https://genderize.io/ response is returning the x-rate-limit headers written in lowercase as can be seen on the image below the library is failing on the `__construct()` of `Meta.php`

![image](https://user-images.githubusercontent.com/113931035/191785534-a7143b28-ab86-4eb0-b749-bb7f26d18df5.png)

**Comment by pixelpeter** [comment]
Fixed using your pull request https://github.com/pixelpeter/laravel-genderize-api-client/pull/3

Thanks for this 👍🏼
